### ISSUE TITLE
`WCS_Query::get_endpoint_title()` args incompatible with WC core `WC_Query::get_endpoint_title()`

### ISSUE THREAD

**Issue by lordspace** [Automattic/woocommerce-subscriptions-core#164]
this is quite simple so I'll just include this.

I am seeing this when I run wp-cli commands such as wp plugin list.

Warning: Declaration of WCS_Query::get_endpoint_title($endpoint) should be compatible with WC_Query::get_endpoint_title($endpoint, $action = '') in /../wp-content/plugins/woocommerce-subscriptions/includes/class-wcs-query.php on line 104

**Comment by HwsDev-01** [comment]
@lordspace I am also experiencing this issue right about now with my woo-subscription plugin since I migrated to my new server. What may be the possible cause of this issue?

**Comment by gree303** [comment]
I'm also having issues. Has anyone a solution to this? ty

**Comment by HwsDev-01** [comment]
@gree303 I was able to fix this.

1. Open file “/wp-content/plugins/woocommerce-subscriptions/includes/class-wcs-query.php”
2. Go to line 104
3. Change public function get_endpoint_title( $endpoint ) to public function get_endpoint_title( $endpoint, $action = '' )

For more on the solution check out:
https://wordpress.org/support/topic/woocommerce-woocommerce-subscriptions-error-in-4-7-0-update/

**Comment by haszari** [comment]
This is a low impact issue – just a compatibility warning. 

However I'm labelling as high priority because we should keep up with WC core changes and this should be a relatively easy fix.

**Comment by haszari** [comment]
Thanks for the report @lordspace !

**Comment by lordspace** [comment]
You're very welcome. It's good to be fixed because there's no point of having extra warnings in the log files.
Thank you

**Comment by AashikP** [comment]
Another report in 6042644-zen

**Comment by maxlaf** [comment]
6371837-zen
This is being treated as a critical error on this user's site. They're not running PHP 8.

```
2023-06-05T19:20:19+00:00 CRITICAL Declaration of WCS_Query::get_endpoint_title($endpoint) must be compatible with WC_Query::get_endpoint_title($endpoint, $action = '') in /home/sites/12b/b/bf8edf18a7/public_html/wp-content/plugins/woocommerce-subscriptions/includes/class-wcs-query.php on line 104
```

**Comment by james-allan** [comment]
The `WCS_Query` class hasn't had a `get_endpoint_title()` function for over 3 years. It was removed back in 2020 as part of this commit https://github.com/Automattic/woocommerce-subscriptions-core/commit/352f08ff0b2bdb3a36ebd2c4f55be316b55e193f.

For internal folks with access to the plugin repo, this is the original PR https://github.com/woocommerce/woocommerce-subscriptions/pull/3857. It was submitted to the plugin repo prior to the splitting of subscriptions-core. 

What's perplexing is the latest report was only last month and the system status suggests they have v5.1.3 of Subscriptions running. The error log entry also indicates it's coming from the old plugin file structure - ie no subscription-core dir in the file trace (`wp-content/plugins/woocommerce-subscriptions/includes/class-wcs-query.php`). That file at that location hasn't existed since the subscriptions-core split. 😕 

With all of that in mind, sites which are still getting this error I can only imagine were running an old version of subscriptions at the time, or the `class-wcs-query.php` file is cached or something. 🤷‍♂️ 

I'm going to close this issue because I cannot replicate it and I can't see how this would be possible running any of the latest versions of WC Subscriptions from the last 3 years. I have a feeling though that something rather strange is happening if folks are still getting this error 3 years after it was fixed.

**Comment by mickaelstrg** [comment]
Just to add my 2 cents here for anybody else coming across this issue in the future: I ran into the same issue with a Wordpress instance that had a version lower than 6.x. All WooCommerce plugins were considered up to date. They weren't and were stuck on an old version. Updating to the latest Wordpress instance allowed WooCommerce plugins (including the Subscriptions plugin) to be updatable. This fixed the issue without having to manually patch the file mentioned here.
