### ISSUE TITLE
Replace 'save_post' hook

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-subscriptions-core#220]
## Describe the bug

There are a number of places in the code that hook into the `save_post` action. These methods will not work with [HPOS](https://developer.woocommerce.com/2022/09/14/high-performance-order-storage-progress-report/) turned on and syncing to CPT turned off.

https://github.com/Automattic/woocommerce-subscriptions-core/blob/3c7ae3489cacd2bf29ea59daf8702c8a914aafc8/includes/class-wc-subscriptions-synchroniser.php#L96
https://github.com/Automattic/woocommerce-subscriptions-core/blob/3c7ae3489cacd2bf29ea59daf8702c8a914aafc8/includes/class-wcs-cached-data-manager.php#L95
https://github.com/Automattic/woocommerce-subscriptions-core/blob/3c7ae3489cacd2bf29ea59daf8702c8a914aafc8/includes/admin/class-wc-subscriptions-admin.php#L90-L91

**Comment by mattallan** [comment]
@brucealdridge thanks for opening this one!

I've just pushed up those changes I made this morning to the [class-wc-subscriptions-synchroniser.php](https://github.com/Automattic/woocommerce-subscriptions-core/blob/3c7ae3489cacd2bf29ea59daf8702c8a914aafc8/includes/class-wc-subscriptions-synchroniser.php#L96):

See the commit/changes here: https://github.com/Automattic/woocommerce-subscriptions-core/pull/224/commits/337dc0e2360dba59d66b8f37aef28919d8902432

My approach was to surround the `add_action (save_post)` line with `if ( wcs_is_custom_order_tables_usage_enabled() ) {` but I'm kind of hoping there's a more elegant way that doesn't mean we have to surround every post hook with this.

Hopefully there's some hook that'll work for both Posts and COT subscriptions

**Comment by haszari** [comment]
Next step here could be a research spike to understand our use cases for `save_post`, and propose alternative hook or approaches. From a quick look, I see two broad patterns in the linked code:

- Updating meta after order/subscription save.
- Clearing caches after "post" save (is this specific to orders/subscriptions?).

If we need a new hook in core (or multiple) then we'll need to start that discussion with core soon.

**Comment by mattallan** [comment]
This issue can be closed as all relevant `save_post` hooks have been updated 🎉 


- **`add_action( 'save_post', 'WC_Subscriptions_Synchroniser::maybe_add_subscription_meta', 10, 1 );`**

This case was addressed in https://github.com/Automattic/woocommerce-subscriptions-core/pull/235

- **`if ( doing_action( 'save_post' ) ) {`**

This code is in a deprecated function that has been deprecated since WC Subscriptions 2.3.0. Instead of updating this code we should remove it as part of a wider change to removing code deprecated since x.x.x

- **`add_action( 'save_post', 'WC_Subscriptions_Admin::save_subscription_meta', 11 );`**
- **`add_action( 'save_post', 'WC_Subscriptions_Admin::save_variable_subscription_meta', 11 );`**

These uses of save post is hooked onto saving products which are staying in posts table so these cases can be ignored.

Before closing this I've looked over our codebase and no other instances of the `save_post` hooks is used so it's safe to close this one off.
