### ISSUE TITLE
WCPay Subscriptions: Show only valid payment methods when editing/creating a subscription via wp-admin

### ISSUE THREAD

**Issue by leonardola** [Automattic/woocommerce-subscriptions-core#29]
Related to https://github.com/Automattic/woocommerce-payments/issues/2962

### Description

When admin create or edit a subscription via admin, **only** allow them to choose WooCommerce Payments or Manual Renew

<img width="503.25" alt="Screen Shot 2021-09-22 at 3 47 00 pm" src="https://user-images.githubusercontent.com/8490476/134289661-421b0a07-8f6c-43a9-b453-e7599c263f0b.png">

### Acceptance criteria

* Manual renewal is the only option if the customer doesn't have any saved cards. 
* WooCommerce Payments is the only option shown if WC Subscriptions (plugin) isn't active.

### Testing instructions

**Creating subscription:**
Test should be done with and without upe active

Case 1
- With WC Payments plugin **active** and WC Subscription **inactive**
- Go to **WooCommerce > Subscriptions > Add new**
- Choose a customer **with** a saved credit card on WCPayments 
- Click the pencil icon in the billing fields section. 
- It should show **only WC Payments**

Case 2
- With WC Payments plugin **active** and WC Subscription **inactive**
- Go to **WooCommerce > Subscriptions > Add new**
- Choose a customer **without** a saved credit card on WCPayments 
- Click the pencil icon in the billing fields section. 
- It should show **only Manual Renewal**

Case 3
- With WC Payments plugin **active** and WC Subscription **active**
- Go to **WooCommerce > Subscriptions > Add new**
- Choose a customer **with** a saved credit card on WCPayments 
- Click the pencil icon in the billing fields section. 
- It should show **Manual Renewal and WC Payments**

**Comment by haszari** [comment]
@james-allan can you confirm whether we should follow up this issue (since you were involved originally)? My understanding is that this is out of scope, though it might be a nice potential enhancement. 

If we do want to include this scope for in 3.3 or 3.4 fast follow fixes, let's move it over to WCPay repo. cc project DRI @aprea

**Comment by james-allan** [comment]
We should change the scope or close this in line with the comment I made on the linked PR https://github.com/Automattic/woocommerce-subscriptions-core/pull/31#issuecomment-968467065.

At the moment, whenever an admin user creates a subscription, the subscription will always be manual. Selecting WooCommerce Payments and selecting a card/token won't actually stick because it will get saved but the subscription will be treated as manual because it doesn't have a WCPay Subscription ID.

**Comment by haszari** [comment]
Thanks James 👍 

> Selecting WooCommerce Payments and selecting a card/token won't actually stick because it will get saved but the subscription will be treated as manual because it doesn't have a WCPay Subscription ID.

@james-allan Let's log that as a separate issue and close this. E.g. the UI shouldn't offer any payment methods, only `Manual renew`.

**Comment by james-allan** [comment]
Closing this one in favour of a new issue to handle the UX issue I mentioned above. Here are the related issues:

WCPay: https://github.com/Automattic/woocommerce-payments/issues/3384
`subscriptions-core`: https://github.com/Automattic/woocommerce-subscriptions-core/issues/47
WC Subscriptions: 4266-gh-woocommerce/woocommerce-subscriptions
