### ISSUE TITLE
Add Hook for Renewal with Custom Subscriptions Status

### ISSUE THREAD

**Issue by ndziuba** [Automattic/woocommerce-subscriptions-core#36]
### Description
In the file **includes/class-wc-subscriptions-manager.php** on **line 89** there is the following check:

`$renewal_order = self::process_renewal( $subscription_id, 'active', $order_note );`

Because of the hardcoded 'active' parameter im unable to add an custom status thats processed with renewal orders.

### Problem
I have implemented an custom status to be able to set custom cancellation processes.
For example to cancel the subscriptions that got canceled every half a year on fixed dates and keep the subscription generate 'next payment dates' till then.
Basicly an 'active status' that got set an 'end date' based on the conditions.
Even tho this works and next payment dates are generated they wont get processed because the process_renewal function gets only called for active status subscriptions.

### Solution

Is it possible to add an hook to add an custom status for the second parameter?
So instead of an hardcoded 'active' status to be able to set an additonal status that should be processed.

Or to be able to override the whole function.

Or even to implement it so the process gets triggered for every status that has 'next payment dates' set.

**Comment by haszari** [comment]
Hi @ndziuba – thanks for reaching out!

Can you give us some more context info to help us prioritise this potential enhancement? 

- Are you integrating with [WooCommerce Subscriptions](https://woocommerce.com/products/woocommerce-subscriptions)? (Assuming yes, this repo also powers the [built-in subscriptions feature in WooCommerce Payments](https://woocommerce.com/document/payments/subscriptions/).)
- Does this problem affect your site, or is this in a plugin or theme that integrates with subscriptions? Feel free to link in your store URL, or theme/plugin.
- Tell us more about your use case and custom status & cancellation flows. What you are trying to achieve, and how this impacts the experience. 
- What workarounds or alternatives have you tried?

Thank you 🙂

**Comment by ndziuba** [comment]
Hi @haszari thanks for your reply

So.. I had it with multiple customers that they want more flexibility when canceling a subscription.
Right now you only have the option to cancel it for the 'already paid term'.

So lets for example say i sell gym subscriptions which goes for a minimum of one year but is payed monthly.
Then i can't cancel them for example in 5 terms but only for the next month (but yes i could calculate a manual end date myself and then send the confirmation manualy which would be a big hassel).

Or if someone got subscriptions with fixed cancelation dates. 
For example the 01.01, 01.04, 01,07 and 01.10 and the cancelation must happen a month in advance. 
If you want to cancel for the 01.07 you would need to send the cancelation before the 01.06. 
Then it would be convinient to have a status that automaticlly calculates the right date of cancelation and confirmes it to the customer via email.

And thats basiclly what i try to acomplish. 
Building a plugin for my customers where they got a custom status thats:

- calculating the right cancelation date automaticly based on set conditions
- giving them a custom status to filter and organise these cancelations (so not just setting manual 'end dates')
- sending cancelation confirmation emails to confirm the calculated end date to the customer (in germany you are legaly required to do that)


I thought that as long as my subscriptions got a 'next payment date' it would trigger a renewal. 
But thats not the case, they get only triggered if the status is 'active' aswell.
The only workaround that i found is to set a cron and trigger the 'wcs_create_renewal_order'.
Which then introduces alot of other problems.
Or to just completly implement the logic myself based on the code in the plugin. But i would like to avoid that.

The easiest way to work around this limitation that i thought off would be to just set the status back to 'active' right before the renewal gets triggered and just save the cancelation date and the if the email got already send as meta data so the email wouldnt be send every time the status gets programaticly applied.
And then just apply the saved status and data back to the subscription after the renewal got processed.


What are your thoughts and how would you solve it?

**Comment by james-allan** [comment]
> Even tho this works and next payment dates are generated they wont get processed because the process_renewal function gets only called for active status subscriptions.

I would be somewhat reluctant to add a filter that simply allows different statuses to renew. Only because it's a fairly fundamental behaviour that subscriptions which aren't active - eg on-hold, cancelled or expired - no longer renew and it's almost certainly going to result in a support burden when a merchant inevitably goes to our support reporting that a customer's cancelled subscription renewed in error. 

The other point to make is that because it's such a fundamental behaviour that inactive subscriptions don't renew, it's likely that even if we did make this status filterable, there would be another roadblock around the calculating or scheduling of the next payment dates and we'd need to make that filterable too. eg In the scheduler class we only schedule events (including renewal payment events), [if the subscription is active](https://github.com/automattic/woocommerce-subscriptions-core/blob/1.0.3/includes/class-wcs-action-scheduler.php#L57-L58). 

In the end, I don't think this specific use case has enough support to open us up to the potential support and maintenance burden but also the potential conflicts with this if we continue to work under the assumption that only active subscriptions should renew and have next payment dates.

---

Having said that, I'm curious to explore how we could achieve this use case using more legitimate alternatives. 

In your message above you mentioned that you could calculate and set the end date. Can you explain why that wouldn't work for you or why it would be too difficult? 

As far as I see it, your scenario would look like this:

1. A customer's subscription renews monthly. 
2. The subscription has a 1-year minimum period - this exists as a business requirement. 
3. Customer cancels the subscription 4 months into their subscription. 
4. Your code could check if the subscription start date was more than a year ago. 
   - If yes, cancel now or at the end of the current month. Default behaviour. 
   - If no, set the end date to be at the 1-year mark and the subscription remains active until then.


> Or if someone got subscriptions with fixed cancellation dates.

You could use the same kind of logic for the other example you mentioned. Depending on when the customer clicks the cancel button, calculate the corresponding cancel date based on the criteria and set of cancellation dates. 

1. Customer hits cancel. Is the customer eligible for the `01.07` cancel date? ie is today before or after `01.06`. 
   - If yes, cancel on the `01.07` date. 
   - If no, they have missed the window and they can only cancel for the `01.08`. or whatever the behaviour might be. 

---

So in general I wouldn't suggest using a different status in these scenarios if you can avoid it. As I mentioned, WC Subscriptions has this fundamental rule of only subscriptions which are active can be renewed and even schedule renewal events, so even if we got over this specific hurdle, we'd run into another one somewhere else down the line. 

Let me know if the examples I mentioned above will work for you or if I'm missing something about this use case.

**Comment by haszari** [comment]
Closing - adding this hook isn't practical. Thanks for reaching out @ndziuba and good luck - if you need additional support please contact our support team here: https://woocommerce.com/my-account/create-a-ticket/
