### ISSUE TITLE
Update our subscriptions-core unit tests to run in a HPOS environment

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-subscriptions-core#391]
## Description

Our subscriptions unit tests contain WP Post functions/hooks (i.e. `update_post_meta()`) which means they cannot be run on environments with HPOS enabled.

This issue is to update all of our unit tests to use WC CRUD apis in place or WP Post functions.

> **Note**
> As part of tackling this issue we will not be enabling HPOS in our CI environment, since that still needs to be decided on.

## Additional context

This came up internally in slack where the team behind AutomateWoo is using functions in the [`WCS_Helper_Subscription`](https://github.com/woocommerce/woocommerce-subscriptions/blob/trunk/tests/framework/helpers/class-wcs-helper-subscription.php) class to create subscriptions.

Slack ref: p1674204479106369-slack-C03SKBVPQ78

**Comment by mikkamp** [comment]
For reference here is the workaround function we are using at the moment: https://github.com/woocommerce/automatewoo/blob/5.6.4/tests/helpers/wcs_helper_subscription.php

It's not as flexible since it doesn't allow setting custom subscription meta, and it appears to be slow when all dates are set, but it's working for now as an alternative.
