### ISSUE TITLE
Allow one-time purchase

### ISSUE THREAD

**Issue by leonardola** [Automattic/woocommerce-subscriptions-core#488]
## Description
It's common for merchants to use Subscriptions with a discounted price as a way to hook customers into a long term relationship with the brand. Right now if a merchant needs to do that they need to pay for and install other extensions alongside with WooCommerce Subscriptions.

This could be a great add to our core/pro plugin.

We even got a [feature request](https://woocommerce.com/pt-br/feature-request/variable-subscription-with-one-time-purchase-option/) from a customer back in 2016

## What's expected
- Merchants should be able to create a subscription product with a price for buying it once and a discounted price when bought as a subscription
- A nice to have is to be able to edit the options label

## Examples
<img width="544" alt="Screenshot 2023-08-01 at 3 28 28 PM" src="https://github.com/Automattic/woocommerce-subscriptions-core/assets/6342964/a0a3a2a7-b36b-42f7-9e06-e54d02d5d46e">

**Different labels**
<img width="764" alt="Screenshot 2023-08-01 at 3 28 57 PM" src="https://github.com/Automattic/woocommerce-subscriptions-core/assets/6342964/d929058e-4b8d-44ca-b4c6-ce435f789f12">

**Multiple options with different discounts**
<img width="516" alt="Screenshot 2023-08-01 at 3 33 32 PM" src="https://github.com/Automattic/woocommerce-subscriptions-core/assets/6342964/4ce535e0-30ca-4547-be52-ded4200f9f96">

**Multiple delivery options with different discounts**
<img width="391" alt="Screenshot 2023-08-01 at 3 36 42 PM" src="https://github.com/Automattic/woocommerce-subscriptions-core/assets/6342964/3736b352-6ea4-4f26-bdae-d0557227c86c">

## Product impact
- [x] Does this feature affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [x] Does this feature affect WooCommerce Payments? yes/no/tbc, add issue ref

## Additional context
This came up during the development of Taika project. [Slack thread](p1690909766123259-slack-C04TEA18D8Q)

## Other extensions
https://woocommerce.com/pt-br/products/buy-once-or-subscribe-for-woocommerce-subscriptions/
https://woocommerce.com/pt-br/products/woocommerce-mix-and-match-products/

**Comment by thenbrent** [comment]
Hey @leonardola thanks for opening this request. The best location for Feature Requests like this is the board you linked too (https://woocommerce.com/feature-requests/woocommerce-subscriptions/) because that system more easily helps compare popularity against requests unlike GitHub, which we use mostly for tracking bug backlog.

That said, I'm going to close this one even though the open request on that board isn't as popular as perhaps demand warrants. That's for two reasons:

1. There is already a way to achieve this functionality via the All Products extension, and usually when there is an extension for it, that makes it much lower priority than feature requests without any suitable approach.
2. Given the above, the request relating to this is not so much "this should be a new feature" as it is "this existing paid extension should be core functionality available after purchasing the extension". That is something we have discussed and debated many times, and it remains a possibility (as discussed in the 2023 and beyond plans here peNgfG-p-p2) but the prioritization decision has other impacts (e.g. lost revenue from sales of that extension.)
