### ISSUE TITLE
Confusing downgrade error notice when activating WC Subscriptions 3.1.6 with WC Pay 3.2+

### ISSUE THREAD

**Issue by aprea** [Automattic/woocommerce-subscriptions-core#7]
WC Subscriptions has an error notice to inform the merchant that they are downgrading, which can be dangerous (e.g. after data upgrades have run). 

https://github.com/Automattic/woocommerce-subscriptions-core/blob/2a0654bf0385cc3e5b097943aea5589e843b05d0/includes/upgrades/class-wc-subscriptions-upgrader.php#L829-L837

<img width="1101" alt="Screen Shot 2021-10-14 at 10 38 31 AM" src="https://user-images.githubusercontent.com/4167300/137216391-441428af-8d93-4676-bafb-cb6144b04cc7.png">

This shows for merchants activating WC Subs 3.1.6 with the current dev WC Pay (forthcoming 3.2, with subscriptions feature). The message is misleading and alarming – it might cause support requests. This combination of plugins should work well and be supported, so ideally there would be no notice in this situation.

### How to reproduce the bug
1. Set up WCPay 3.2/`develop` branch in your dev env and make sure you are onboarded.
2. Ensure WCPay Subscriptions is enabled - set option `_wcpay_feature_subscriptions` to `1` or use dev tools plugin.
3. Install and activate WC Subscriptions 3.1.6.

#### Expected behaviour
No error!

Possibly something congratulatory, e.g. : congratulations on upgrading to WC Subscriptions, you now have access to more features, flexibility and other payment gateways. 

#### Actual behaviour
Error notice with links to open a support ticket: `Warning! It appears that you have downgraded WooCommerce Subscriptions from 4.0.0 to 3.1.6. Downgrading the plugin in this way may cause issues. Please update to 4.0.0 or higher, or [open a new support ticket] for further assistance. [Learn more »]`

### Possible solutions
- Change the wording etc of the message for specific version combinations.
- Make the notice dismissable.
- Release an updated WC Subscriptions. This would address the issue in the newest combination, though it would still occur if merchants use old subs zip, and we may hit the issue again as new versions are released.
- Use a different versioning system for subs core library and/or WCPay Subs feature. I'm not sure if this would fix, but could be part of a fix.

### Impact?
I'm not clear on how common this scenario might be. If it's rare that merchants would actually see this message, maybe ok to de-prioritise.

However this notice is a symptom that there are some changed assumptions, so it would be good if we could get ahead of that.

Slack discussion p1634009219292300-slack-C02BW3Z8SHK

**Comment by haszari** [comment]
Assigning myself to clarify the problem / impact and scope out solutions. If anyone wants to start work on this go for it :)

**Comment by mattallan** [comment]
The main cause to this problem is that in WCS Core, we've set the plugin version to be 4.0.0 so without us needing to do a release of WC Subscriptions, there's a couple of things we can do to fix this:

There's a couple of way I'm thinking we could fix this:

- Update the [plugin version](https://github.com/Automattic/woocommerce-subscriptions-core/blob/trunk/includes/class-wc-subscriptions-core-plugin.php#L20) we have set in `subscriptions-core` to be 3.1.6 for the initial release (at least until we have released 4.0.0 of our extension)
- Update this check in [this condition](https://github.com/Automattic/woocommerce-subscriptions-core/blob/2a0654bf0385cc3e5b097943aea5589e843b05d0/includes/upgrades/class-wc-subscriptions-upgrader.php#L825) to only show this notice if store managers have downgraded all the way back to.

This notice was originally added to Subscriptions to notify store managers that have downgraded from 2.0 back to 1.5. This is because 2.0 changed Subscriptions significantly from an array stored on an order, to a custom order type, so downgrading back to 1.5 was really bad.

These days downgrading from Subscriptions 4.0 to 3.0 isn't a big deal at all so I think updating when the condition is shown is a fine approach.

That said, if we update this notice to only show when stores downgrade to 1.5, we'll also need to add this change to WC Subscriptions and do a 3.1.7 release which isn't ideal.

For that reason I think the best approach is to just update the Plugin version we have in core to 3.1.6 (the latest public WC Subscriptions version) and then when we release 4.0 we can update the plugin version in Core.

I've assigned myself this issue to take a look at this

**Comment by haszari** [comment]
Thanks @mattallan for tidying this up!

> These days downgrading from Subscriptions 4.0 to 3.0 isn't a big deal at all so I think updating when the condition is shown is a fine approach.

Do you think it's worthwhile looking at this too - either in same PR or as follow up later? E.g. tighten up the use of the notice so it's shown less often, only for specifically dangerous downgrades.

**Comment by mattallan** [comment]
>  either in same PR or as follow up later?

This isn't a priority so I've created a low priority issue to look at this later on. See #12

**Comment by haszari** [comment]
Just an FYI - I see the message again when updating my test store to the latest WCPay with Subscriptions (no subscriptions plugin). I think that's to be expected, since the new WCPay build has older version 3.1.6, and the version I'm overwriting (previous dev build) had version 4.0. This should not affect anyone other than developers testing dev builds :)
